# Generated by Django 5.2.15 on 2026-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='設定名稱')),
                ('channel_id', models.CharField(max_length=30, verbose_name='頻道 ID')),
                ('channel_type', models.CharField(choices=[('crawl', '爬取頻道'), ('news', '新聞推播頻道')], default='crawl', max_length=20, verbose_name='頻道類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('note', models.TextField(blank=True, verbose_name='備注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discord Bot 設定',
                'verbose_name_plural': 'Discord Bot 設定',
            },
        ),
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=30, unique=True, verbose_name='訊息 ID')),
                ('channel_id', models.CharField(db_index=True, max_length=30, verbose_name='頻道 ID')),
                ('channel_name', models.CharField(blank=True, max_length=200, verbose_name='頻道名稱')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='發送時間')),
                ('is_umamusume', models.BooleanField(db_index=True, null=True, verbose_name='是否馬娘相關')),
                ('classified_by', models.CharField(blank=True, choices=[('keyword', '關鍵字'), ('gemini', 'Gemini AI'), ('', '未分類')], max_length=20, verbose_name='分類方式')),
                ('news_data_id', models.CharField(blank=True, max_length=50, verbose_name='對應 NewsData ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discord 訊息',
                'verbose_name_plural': 'Discord 訊息',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiscordNewsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=30, verbose_name='推播頻道 ID')),
                ('content', models.TextField(verbose_name='推播內容')),
                ('model_used', models.CharField(max_length=50, verbose_name='使用的 AI 模型')),
                ('message_ids', models.TextField(blank=True, verbose_name='Discord 訊息 ID 清單（逗號分隔）')),
                ('status', models.CharField(choices=[('sent', '已推播'), ('failed', '失敗'), ('pending', '待推播')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discord 新聞推播紀錄',
                'verbose_name_plural': 'Discord 新聞推播紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
