# Generated by Django 5.2.15 on 2026-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_discord_bot', '0002_add_guild_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('crawl', '爬取頻道訊息'), ('classify', '分類待分類訊息'), ('convert', '轉換至 NewsData'), ('news', '手動推播 AI 新聞')], db_index=True, max_length=20, verbose_name='任務類型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('success', '成功'), ('failed', '失敗'), ('cancelled', '取消')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, verbose_name='進度百分比')),
                ('estimated_seconds', models.PositiveIntegerField(default=0, verbose_name='預估秒數')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='開始時間')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('triggered_by', models.CharField(blank=True, default='admin-ui', max_length=60, verbose_name='觸發來源')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='摘要')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='錯誤訊息')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='結果 JSON')),
                ('log_text', models.TextField(blank=True, default='', verbose_name='執行日誌')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord 任務執行記錄',
                'verbose_name_plural': 'Discord 任務執行記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
