# Generated by Django 5.2.15 on 2026-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_discord_bot', '0003_discordtaskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCrawlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_limit', models.IntegerField(default=1000, verbose_name='每頻道訊息上限（0 = 不限）')),
                ('concurrency', models.IntegerField(default=3, verbose_name='並行頻道數（1–10）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '爬取全域設定',
                'verbose_name_plural': '爬取全域設定',
            },
        ),
    ]
