# Generated by Django 5.2.15 on 2026-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_discord_bot', '0004_add_discord_crawl_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordtaskrun',
            name='cancel_requested',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已請求取消'),
        ),
        migrations.AddField(
            model_name='discordtaskrun',
            name='runner',
            field=models.CharField(choices=[('bot', '持久 Bot 行程'), ('thread', 'Django 執行緒')], default='thread', max_length=10, verbose_name='執行方式'),
        ),
    ]
