# Generated by Django 5.2.13 on 2026-05-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_uma_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_score', models.FloatField(blank=True, null=True, verbose_name='正面機率 (0~1)')),
                ('negative_score', models.FloatField(blank=True, null=True, verbose_name='負面機率 (0~1)')),
                ('neutral_score', models.FloatField(blank=True, null=True, verbose_name='中立機率 (0~1)')),
                ('excited', models.FloatField(default=0.0, verbose_name='興奮 (%)')),
                ('happy', models.FloatField(default=0.0, verbose_name='開心 (%)')),
                ('mixed', models.FloatField(default=0.0, verbose_name='五味雜陳 (%)')),
                ('disappointed', models.FloatField(default=0.0, verbose_name='失望 (%)')),
                ('angry', models.FloatField(default=0.0, verbose_name='生氣 (%)')),
                ('sad', models.FloatField(default=0.0, verbose_name='悲傷 (%)')),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI 模型')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析時間')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='app_uma_news.gameannouncement', verbose_name='所屬公告')),
            ],
            options={
                'verbose_name': '留言情緒分析',
                'verbose_name_plural': '留言情緒分析',
            },
        ),
    ]
