# Generated by Django 5.2.15 on 2026-06-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment_sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='標題')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='網址')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分類')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='發佈日期')),
                ('source', models.CharField(default='bahamut', max_length=100, verbose_name='來源')),
                ('positive_score', models.FloatField(blank=True, null=True, verbose_name='正面機率 (0~1)')),
                ('negative_score', models.FloatField(blank=True, null=True, verbose_name='負面機率 (0~1)')),
                ('neutral_score', models.FloatField(blank=True, null=True, verbose_name='中立機率 (0~1)')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='情緒分析時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '哈啦板文章',
                'verbose_name_plural': '哈啦板文章',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheer_up', models.FloatField(default=0.0, verbose_name='加油 (%)')),
                ('happy', models.FloatField(default=0.0, verbose_name='開心 (%)')),
                ('mixed', models.FloatField(default=0.0, verbose_name='五味雜陳 (%)')),
                ('dumbfounded', models.FloatField(default=0.0, verbose_name='傻眼 (%)')),
                ('angry', models.FloatField(default=0.0, verbose_name='生氣 (%)')),
                ('sad', models.FloatField(default=0.0, verbose_name='悲傷 (%)')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='app_comment_sentiment.article', verbose_name='所屬文章')),
            ],
            options={
                'verbose_name': '文章情緒六維度',
                'verbose_name_plural': '文章情緒六維度',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('upvotes', models.IntegerField(default=0, verbose_name='讚數')),
                ('downvotes', models.IntegerField(default=0, verbose_name='噓數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_comment_sentiment.article', verbose_name='所屬文章')),
            ],
            options={
                'verbose_name': '哈啦板留言',
                'verbose_name_plural': '哈啦板留言',
            },
        ),
    ]
