# Generated by Django 5.2.13 on 2026-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內文')),
                ('category', models.CharField(choices=[('活動', '活動'), ('卡池', '卡池'), ('競賽', '競賽'), ('系統', '系統'), ('其他', '其他')], default='其他', max_length=50, verbose_name='類別')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='來源連結')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='發布日期')),
                ('source', models.CharField(default='bilibili', max_length=20, verbose_name='資料來源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='匯入時間')),
            ],
            options={
                'verbose_name': '遊戲公告',
                'verbose_name_plural': '遊戲公告',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
