# Generated by Django 5.2.15 on 2026-06-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('channel_id', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube 影片',
                'verbose_name_plural': 'YouTube 影片',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='app_youtube_publish_32cc1b_idx'), models.Index(fields=['view_count'], name='app_youtube_view_co_3bc0aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('comment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_youtube_uma.youtubevideo')),
            ],
            options={
                'verbose_name': 'YouTube 留言',
                'verbose_name_plural': 'YouTube 留言',
                'ordering': ['-like_count'],
            },
        ),
    ]
