# Generated by Django 5.2.15 on 2026-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube_uma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeQuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('units_used', models.IntegerField(default=0, verbose_name='已用配額')),
                ('units_limit', models.IntegerField(default=10000, verbose_name='配額上限')),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True, verbose_name='最後爬取時間')),
                ('videos_added', models.IntegerField(default=0, verbose_name='本次新增影片數')),
            ],
            options={
                'verbose_name': 'YouTube 配額記錄',
                'verbose_name_plural': 'YouTube 配額記錄',
                'ordering': ['-date'],
            },
        ),
    ]
