# Generated by Django 5.2.13 on 2026-05-27 04:49

import app_crawler_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crawler_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crawlerrun',
            name='run_id',
            field=models.CharField(default=app_crawler_admin.models._default_run_id, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crawlerschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
