# Generated by Django 5.2.15 on 2026-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uma_info_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guildchannelcache',
            name='unique_guild_channel_cache',
        ),
        migrations.RemoveConstraint(
            model_name='guildchannelrule',
            name='unique_guild_channel_rule',
        ),
        migrations.RemoveConstraint(
            model_name='guildrolecache',
            name='unique_guild_role_cache',
        ),
        migrations.AddField(
            model_name='guildchannelcache',
            name='bot_can_read',
            field=models.BooleanField(default=True, verbose_name='Bot 可讀取（view+history）'),
        ),
        migrations.AddField(
            model_name='guildchannelcache',
            name='bot_can_send',
            field=models.BooleanField(default=True, verbose_name='Bot 可發訊息（send+embed）'),
        ),
        migrations.AlterField(
            model_name='discordguild',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guildchannelcache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guildchannelrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guildrolecache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guildsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guildsettingaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='guildchannelcache',
            unique_together={('guild', 'channel_id')},
        ),
        migrations.AlterUniqueTogether(
            name='guildchannelrule',
            unique_together={('guild', 'channel_id')},
        ),
        migrations.AlterUniqueTogether(
            name='guildrolecache',
            unique_together={('guild', 'role_id')},
        ),
    ]
