# Generated by Django 5.2.15 on 2026-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('mention_count', models.IntegerField()),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('window_days', models.IntegerField(default=0)),
                ('computed_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['category', '-mention_count'], name='app_uma_top_categor_f4520a_idx'), models.Index(fields=['computed_date', 'window_days'], name='app_uma_top_compute_697c23_idx')],
                'unique_together': {('character', 'category', 'source', 'window_days', 'computed_date')},
            },
        ),
    ]
