# Generated by Django 5.2.13 on 2026-05-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('photo_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tokens_filtered', models.TextField(blank=True, null=True)),
                ('token_pos', models.TextField(blank=True, null=True)),
                ('top_key_freq', models.TextField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
