# Generated by Django 5.2.13 on 2026-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_keyword_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='source',
            field=models.CharField(default='bilibili', max_length=20),
        ),
    ]
