# Generated by Django 5.2.15 on 2026-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_keyword_db', '0002_newsdata_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='status',
            field=models.CharField(choices=[('raw', '已爬取'), ('tokenized', '已斷詞'), ('labeled', '已情感標記')], db_index=True, default='raw', max_length=20),
        ),
    ]
