# Generated by Django 5.2.15 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_keyword_db', '0003_newsdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmaCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tw', models.CharField(max_length=100, unique=True)),
                ('name_jp', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('icon_url', models.URLField(blank=True, max_length=600)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '賽馬娘角色',
                'verbose_name_plural': '賽馬娘角色',
                'ordering': ['name_tw'],
            },
        ),
    ]
