# Generated by Django 5.2.13 on 2026-05-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_uma_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='留言者')),
                ('upvotes', models.IntegerField(default=0, verbose_name='讚數')),
                ('downvotes', models.IntegerField(default=0, verbose_name='倒讚數')),
                ('floor', models.IntegerField(default=0, verbose_name='樓層')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取時間')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_uma_news.gameannouncement', verbose_name='所屬公告')),
            ],
            options={
                'verbose_name': '玩家留言',
                'verbose_name_plural': '玩家留言',
                'ordering': ['-upvotes', 'floor'],
            },
        ),
    ]
